services:
  # Backend Django приложение
  backend:
    build:
      context: ./django_rest_api # Путь к папке с Django проектом
    ports:
      - "8000:8000"
    depends_on:
      - db  # Зависимость от сервиса базы данных
    environment:
      - DATABASE_URL=postgres://postgres:12345678@db:5432/cortex-postgres-container  # URL для подключения к базе данных
    command: ./entrypoint.sh  # Используем entrypoint.sh для запуска

  # База данных PostgreSQL
  db:
    image: postgres
    environment:
      - POSTGRES_DB=cortex-postgres-container
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Монтирование тома для сохранения данных

  # Фронтенд
  frontend:
    build:
      context: ./frontend  # Путь к папке с фронтенд проектом
    ports:
      - "3000:3000"  # Проброс портов для доступа к фронтенду
    depends_on:
      - backend  # Зависимость от бэкенда

volumes: # Определение томов
  postgres_data:  # Название тома, используемое в сервисе db